# Generated by Django 5.0.14 on 2026-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intent',
        ),
        migrations.AddField(
            model_name='querylog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
